/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.ListaDeTarefas;

import com.example.ListaDeTarefas.model.ConexaoSQLite;
import com.example.ListaDeTarefas.model.CriarTabela;
import java.sql.Connection;

public class App {

    public static void main(String[] args) {
        Connection conexao = ConexaoSQLite.conectar();
        
        CriarTabela.criarTabelaTarefas(conexao);
        
        //Aqui o JFrame é chamado
    }
}
